# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: mkdir staging
    - run: mvn -B package --file jareto-common/pom.xml
    - run: cp jareto-common/target/*.jar staging
    - run: mvn -B package --file jareto-client/pom.xml
    - run: cp jareto-client/target/*.jar staging
    - name: upload (persist) built artifacts
      uses: actions/upload-artifact@v2
      with:
        name: jareto
        path: staging
